/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
if(!window.Typekit)window.Typekit={};window.Typekit.config={"a":"559807","c":[".tk-museo-sans","\"museo-sans\",sans-serif"],"f":"//use.typekit.net/c/02c69e/1w;museo-sans,2,PyB:H:i3,Py8:H:n1,Py6:H:n3,PyC:H:n5,PyF:H:n7/{format}{/extras*}?3bb2a6e53c9684ffdc9a9bf1125b2a62195b0e5cd45ecc8c1363e407b42f76786c688606c77a4b3e3b69beea5439c470981cb44fb16807f9dc496ce59d6aff4bdd7041972ed6712897063837dd79527f8a4486fd824d19a3223e6122f9d2a7180b56f70a7fbdf9b6e23999a4830617c435640392d8564aa43beafd3c8b5c547e39c707c6d00e48630d7d2007d30b400e6444af9944e36584a0b113f84b51c0dc302bd73078974bcf0cd0b3f3ed6b62430ad0","fi":[2006,2005,2009,2003,2007],"fn":["museo-sans",["i3","n1","n3","n5","n7"]],"ht":"tk","k":"//use.typekit.net/{id}.js","kt":"pbn3dxg","p":"//p.typekit.net/p.gif?s=1&k=pbn3dxg&ht=tk&h={host}&f=2006.2005.2009.2003.2007&a=559807&_={_}","ps":1,"w":"pbn3dxg"};
/*{"k":"1.5.0","created":"2013-03-28T14:41:59Z"}*/
;(function(window,document,undefined){
var g=void 0,k=!0,l=null,m=!1;function n(a){return function(){return this[a]}}var p;this.ab=k;function aa(a,c,b){return a.call.apply(a.bind,arguments)}function ba(a,c,b){if(!a)throw Error();if(2<arguments.length){var e=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,e);return a.apply(c,b)}}return function(){return a.apply(c,arguments)}}
function q(a,c,b){q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?aa:ba;return q.apply(l,arguments)}var ca=Date.now||function(){return+new Date};function s(a,c){this.Ra=a;this.ua=c||a;this.j=this.ua.document;this.z=g}s.prototype.createElement=function(a,c,b){a=this.j.createElement(a);if(c)for(var e in c)c.hasOwnProperty(e)&&("style"==e?this.fa(a,c[e]):a.setAttribute(e,c[e]));b&&a.appendChild(this.j.createTextNode(b));return a};
function t(a,c,b){a=a.j.getElementsByTagName(c)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(b,a.lastChild)}function fa(a){function c(){document.body?a():setTimeout(c,0)}c()}function v(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return;b.push(c);a.className=b.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}
function w(a,c){for(var b=a.className.split(/\s+/),e=[],d=0,f=b.length;d<f;d++)b[d]!=c&&e.push(b[d]);a.className=e.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ga(a,c){for(var b=a.className.split(/\s+/),e=0,d=b.length;e<d;e++)if(b[e]==c)return k;return m}s.prototype.fa=function(a,c){this.ca()?a.setAttribute("style",c):a.style.cssText=c};s.prototype.ca=function(){if(this.z===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.z=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.z};
function x(a,c,b){this.hb=a;this.Ba=c;this.gb=b}function y(a,c,b,e,d,f,h,j){this.ea=a;this.$a=c;this.Ga=b;this.Fa=e;this.Va=d;this.Ua=f;this.Ea=h;this.A=j}p=y.prototype;p.getName=n("ea");p.getVersion=n("$a");p.getEngine=n("Ga");p.getEngineVersion=n("Fa");p.getPlatform=n("Va");p.getPlatformVersion=n("Ua");p.getDocumentMode=n("Ea");function ha(a,c){this.e=a;this.u=c}var ia=new y("Unknown","Unknown","Unknown","Unknown","Unknown","Unknown",g,new x(m,m,m));
ha.prototype.parse=function(){var a;if(-1!=this.e.indexOf("MSIE")){a=z(this);var c=B(this),b=C(this.e,/(MSIE [\d\w\.]+)/,1);if(""!=b){var e=b.split(" "),b=e[0],e=e[1],d=D(e),f=D(c);a=new y(b,e,b,e,a,c,E(this.u),new x("Windows"==a&&6<=d.l||"Windows Phone"==a&&8<=f.l,m,m))}else a=new y("MSIE","Unknown","MSIE","Unknown",a,c,E(this.u),new x(m,m,m))}else if(-1!=this.e.indexOf("Opera"))a=ja(this);else if(/AppleWeb(K|k)it/.test(this.e)){a=z(this);var c=B(this),b=C(this.e,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,
1),h=m;""==b&&(b="Unknown");e=D(b);h=D(c);d="Unknown";-1!=this.e.indexOf("Chrome")||-1!=this.e.indexOf("CrMo")||-1!=this.e.indexOf("CriOS")?d="Chrome":/Silk\/\d/.test(this.e)?d="Silk":"BlackBerry"==a||"Android"==a?d="BuiltinBrowser":-1!=this.e.indexOf("Safari")?d="Safari":-1!=this.e.indexOf("AdobeAIR")&&(d="AdobeAIR");f="Unknown";"BuiltinBrowser"==d?f="Unknown":/Silk\/\d/.test(this.e)?f=C(this.e,/Silk\/([\d\._]+)/,1):-1!=this.e.indexOf("Version/")?f=C(this.e,/Version\/([\d\.\w]+)/,1):"Chrome"==d?
f=C(this.e,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):"AdobeAIR"==d&&(f=C(this.e,/AdobeAIR\/([\d\.]+)/,1));"AdobeAIR"==d?(h=D(f),h=2<h.l||2==h.l&&5<=h.v):h="BlackBerry"==a?10<=h.l:"Android"==a?2<h.l||2==h.l&&1<h.v:526<=e.l||525<=e.l&&13<=e.v;a=new y(d,f,"AppleWebKit",b,a,c,E(this.u),new x(h,536>e.l||536==e.l&&11>e.v,"iPhone"==a||"iPad"==a||"iPod"==a||"Macintosh"==a))}else-1!=this.e.indexOf("Gecko")?(c=a="Unknown",b=m,-1!=this.e.indexOf("Firefox")?(a="Firefox",e=C(this.e,/Firefox\/([\d\w\.]+)/,1),""!=e&&
(b=D(e),c=e,b=3<=b.l&&5<=b.v)):-1!=this.e.indexOf("Mozilla")&&(a="Mozilla"),e=C(this.e,/rv:([^\)]+)/,1),""==e?e="Unknown":b||(b=D(e),b=1<b.l||1==b.l&&9<b.v||1==b.l&&9==b.v&&2<=b.Ta||e.match(/1\.9\.1b[123]/)!=l||e.match(/1\.9\.1\.[\d\.]+/)!=l),a=new y(a,c,"Gecko",e,z(this),B(this),E(this.u),new x(b,m,m))):a=ia;return a};
function z(a){var c=C(a.e,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=c)return/BB\d{2}/.test(c)&&(c="BlackBerry"),c;a=C(a.e,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function B(a){var c=C(a.e,/(OS X|Windows NT|Android|CrOS) ([^;)]+)/,2);return c||(c=C(a.e,/Windows Phone( OS)? ([^;)]+)/,2))||(c=C(a.e,/(iPhone )?OS ([\d_]+)/,2))||(c=C(a.e,/Linux ([i\d]+)/,1))?c:(a=C(a.e,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function ja(a){var c="Unknown",b="Unknown",e=C(a.e,/(Presto\/[\d\w\.]+)/,1);""!=e?(b=e.split("/"),c=b[0],b=b[1]):(-1!=a.e.indexOf("Gecko")&&(c="Gecko"),e=C(a.e,/rv:([^\)]+)/,1),""!=e&&(b=e));if(-1!=a.e.indexOf("Opera Mini/"))return e=C(a.e,/Opera Mini\/([\d\.]+)/,1),""==e&&(e="Unknown"),new y("OperaMini",e,c,b,z(a),B(a),E(a.u),new x(m,m,m));if(-1!=a.e.indexOf("Version/")){var d=C(a.e,/Version\/([\d\.]+)/,1);if(""!=d)return e=D(d),new y("Opera",d,c,b,z(a),B(a),E(a.u),new x(10<=e.l,m,m))}d=C(a.e,/Opera[\/ ]([\d\.]+)/,
1);return""!=d?(e=D(d),new y("Opera",d,c,b,z(a),B(a),E(a.u),new x(10<=e.l,m,m))):new y("Opera","Unknown",c,b,z(a),B(a),E(a.u),new x(m,m,m))}function D(a){a=/([0-9]+)(?:\.([0-9]+)(?:\.([0-9]+)?)?)?/.exec(a);var c={};a&&(c.l=parseInt(a[1]||-1,10),c.v=parseInt(a[2]||-1,10),c.Ta=parseInt(a[3]||-1,10));return c}function C(a,c,b){return(a=a.match(c))&&a[b]?a[b]:""}function E(a){if(a.documentMode)return a.documentMode}function ka(a){this.Pa=a||"-"}
ka.prototype.h=function(a){for(var c=[],b=0;b<arguments.length;b++)c.push(arguments[b].replace(/[\W_]+/g,"").toLowerCase());return c.join(this.Pa)};function la(a,c,b){this.g=a;this.m=c;this.ma=b;this.q="wf";this.n=new ka("-")}function H(a){w(a.m,a.n.h(a.q,"loading"));ga(a.m,a.n.h(a.q,"active"))||v(a.m,a.n.h(a.q,"inactive"));I(a,"inactive")}function I(a,c,b,e){if(a.ma[c])a.ma[c](b,e)}function ma(){this.za="'"}
ma.prototype.quote=function(a){var c=[];a=a.split(/,\s*/);for(var b=0;b<a.length;b++){var e=a[b].replace(/['"]/g,"");-1==e.indexOf(" ")?c.push(e):c.push(this.za+e+this.za)}return c.join(",")};function na(){this.xa=oa;this.P=pa}var oa=["font-style","font-weight"],pa={"font-style":[["n","normal"],["i","italic"],["o","oblique"]],"font-weight":[["1","100"],["2","200"],["3","300"],["4","400"],["5","500"],["6","600"],["7","700"],["8","800"],["9","900"],["4","normal"],["7","bold"]]};
function qa(a,c,b){this.Oa=a;this.Wa=c;this.P=b}qa.prototype.expand=function(a,c){for(var b=0;b<this.P.length;b++)if(c==this.P[b][0]){a[this.Oa]=this.Wa+":"+this.P[b][1];break}};na.prototype.expand=function(a){if(2!=a.length)return l;for(var c=[l,l],b=0,e=this.xa.length;b<e;b++){var d=this.xa[b];(new qa(b,d,this.P[d])).expand(c,a.substr(b,1))}return c[0]&&c[1]?c.join(";")+";":l};function J(a,c){this.g=a;this.L=c;this.Sa=new ma;this.Ja=new na;this.B=this.g.createElement("span",{},this.L)}
function K(a,c,b){b=b?a.Ja.expand(b):"";c="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+a.Sa.quote(c)+";"+b;a.g.fa(a.B,c)}function ra(a){t(a.g,"body",a.B)}J.prototype.remove=function(){var a=this.B;a.parentNode&&a.parentNode.removeChild(a)};
function sa(a,c,b,e,d,f,h,j,r){this.ha=a;this.Na=c;this.g=b;this.S=e;this.R=d;this.L=r||"BESbswy";this.A=f;this.O={};this.ga=h||5E3;this.va=j||l;this.K=this.J=l;a=new J(this.g,this.L);ra(a);for(var A in L)L.hasOwnProperty(A)&&(K(a,L[A],this.R),this.O[L[A]]=a.B.offsetWidth);a.remove()}var L={eb:"serif",cb:"sans-serif",bb:"monospace"};
sa.prototype.start=function(){this.J=new J(this.g,this.L);ra(this.J);this.K=new J(this.g,this.L);ra(this.K);this.Ya=ca();K(this.J,this.S+",serif",this.R);K(this.K,this.S+",sans-serif",this.R);ta(this)};function ua(a,c,b){for(var e in L)if(L.hasOwnProperty(e)&&c===a.O[L[e]]&&b===a.O[L[e]])return k;return m}
function ta(a){var c=a.J.B.offsetWidth,b=a.K.B.offsetWidth;c===a.O.serif&&b===a.O["sans-serif"]||a.A.Ba&&ua(a,c,b)?ca()-a.Ya>=a.ga?a.A.Ba&&ua(a,c,b)&&(a.va===l||a.va.hasOwnProperty(a.S))?va(a,a.ha):va(a,a.Na):setTimeout(q(function(){ta(this)},a),25):va(a,a.ha)}function va(a,c){a.J.remove();a.K.remove();c(a.S,a.R)}function M(a,c,b,e){this.g=c;this.C=b;this.$=0;this.Aa=this.ra=m;this.ga=e;this.A=a.A}
M.prototype.watch=function(a,c,b,e,d){var f=a.length;if(0===f)H(this.C);else{for(var h=0;h<f;h++){var j=a[h];c[j]||(c[j]=["n4"]);this.$+=c[j].length}d&&(this.ra=d);for(h=0;h<f;h++){j=a[h];d=c[j];for(var r=b[j],A=0,F=d.length;A<F;A++){var V=d[A],u=this.C,G=j,P=V;v(u.m,u.n.h(u.q,G,P,"loading"));I(u,"fontloading",G,P);u=q(this.Ha,this);G=q(this.Ia,this);(new e(u,G,this.g,j,V,this.A,this.ga,l,r)).start()}}}};
M.prototype.Ha=function(a,c){var b=this.C;w(b.m,b.n.h(b.q,a,c,"loading"));w(b.m,b.n.h(b.q,a,c,"inactive"));v(b.m,b.n.h(b.q,a,c,"active"));I(b,"fontactive",a,c);this.Aa=k;wa(this)};M.prototype.Ia=function(a,c){var b=this.C;w(b.m,b.n.h(b.q,a,c,"loading"));ga(b.m,b.n.h(b.q,a,c,"active"))||v(b.m,b.n.h(b.q,a,c,"inactive"));I(b,"fontinactive",a,c);wa(this)};
function wa(a){0==--a.$&&a.ra&&(a.Aa?(a=a.C,w(a.m,a.n.h(a.q,"loading")),w(a.m,a.n.h(a.q,"inactive")),v(a.m,a.n.h(a.q,"active")),I(a,"active")):H(a.C))}function N(a,c){this.Ra=a;this.ua=c||a;this.j=document;this.z=g}N.prototype=s.prototype;function O(a){return"https:"==a.j.location.protocol}N.prototype.Ka=function(){return this.j.location.hostname};
function xa(a,c,b){var e=a.j.getElementsByTagName("head")[0];if(e){var d=a.j.createElement("script");d.src=c;var f=m;d.onload=d.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=k,b&&b(),d.onload=d.onreadystatechange=l,"HEAD"==d.parentNode.tagName&&e.removeChild(d)};e.appendChild(d)}}N.prototype.fa=function(a,c){this.ca()?a.setAttribute("style",c):a.style.cssText=c};
N.prototype.ca=function(){if(this.z===g){var a=this.j.createElement("p");a.innerHTML='<a style="top:1px;">w</a>';this.z=/top/.test(a.getElementsByTagName("a")[0].getAttribute("style"))}return this.z};function ya(){var a=[{name:"font-family",value:Q.c[i+1]}];this.Xa=[Q.c[i]];this.na=a}function za(a){for(var c=a.Xa.join(","),b=[],e=0;e<a.na.length;e++){var d=a.na[e];b.push(d.name+":"+d.value+";")}return c+"{"+b.join("")+"}"}
function Aa(a,c,b,e){this.I=a;this.T=c;this.La=b;this.fb=e;this.pa={};this.oa={}}Aa.prototype.D=function(a){return a?(this.pa[a.U]||this.T).slice(0):this.T.slice(0)};Aa.prototype.watch=function(a,c,b){var e=[],d={};Ba(this,c,e,d);a(e,d,b)};function Ba(a,c,b,e){b.push(a.I);e[a.I]=a.D(c);a=a.oa[c.U]||[];for(c=0;c<a.length;c++){for(var d=a[c],f=d.I,h=m,j=0;j<b.length;j++)b[j]==f&&(h=k);h||(b.push(f),e[f]=d.D())}}function Ca(a,c){this.I=a;this.T=c}Ca.prototype.D=n("T");
function R(a,c,b){this.La=a;this.U=c;this.qa=b}function Da(){this.ka=this.Da=this.r=this.M=this.N=k}function S(a){Ea.X.push(a)}function Fa(a){this.g=a;this.la=this.t=this.e=this.W=l;this.o=[];this.Q=[];this.Ca=this.aa=this.Y=this.Z=l}
function Ga(a,c){a.e=c;if(a.W){var b;a:{b=a.W;for(var e=a.e,d=a.la,f=0;f<b.X.length;f++){var h=b.X[f],j=e,r=d;r||(r=new Da);if(h.qa&&h.qa(j.getName(),j.getVersion(),j.getEngine(),j.getEngineVersion(),j.getPlatform(),j.getPlatformVersion(),j.getDocumentMode(),r)){b=h;break a}}b=l}a.t=b}}p=Fa.prototype;p.supportsConfiguredBrowser=function(){return!!this.t};
p.init=function(){if(0<this.Q.length){for(var a=[],c=0;c<this.Q.length;c++)a.push(za(this.Q[c]));var c=this.g,a=a.join(""),b=this.g.j.createElement("style");b.setAttribute("type","text/css");b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a));t(c,"head",b)}};
p.load=function(a,c){var b=this.t.U;if(this.aa){var e;e=this.aa;var d=e.G[b];e=d?Ha(e,d):l;for(d=0;d<this.o.length;d++){for(var f=this.o[d],h=this.t,j=e,r=[],A=f.I.split(",")[0].replace(/"|'/g,""),F=f.D(),V=r,u=g,G=[],P={},da=0;da<F.length;da++)u=F[da],0<u.length&&!P[u]&&(P[u]=k,G.push(u));F=G;j=j.ya?j.ya(A,F,V):F;h=h.U;f.pa[h]=j;f.oa[h]=r}}if(this.Z){e=[];if(this.Y){e=new Ia(this.g,this.t,this.o);d=[];f=this.Y.H[b]||[];for(r=0;r<f.length;r++){a:switch(f[r]){case "observeddomain":h=new Ja(e.g);break a;
case "fontmask":h=new Ka(e.t,e.o);break a;default:h=l}h&&d.push(h)}e=d}d=[];for(f=0;f<e.length;f++)d.push(e[f].toString());b=this.Z.h(O(this.g),{format:b,extras:d});t(this.g,"head",this.g.createElement("link",{rel:"stylesheet",href:b}))}if(a){var ea=this,db=this.t;fa(function(){for(var b=0;b<ea.o.length;b++)ea.o[b].watch(a,db,c&&b==ea.o.length-1)})}};p.collectFontFamilies=function(a,c){for(var b=0;b<this.o.length;b++)Ba(this.o[b],this.t,a,c)};
p.performOptionalActions=function(){if(this.da){var a=this,c=this.e,b=this.g;fa(function(){var e=a.da;if(e.wa){var d=window.__adobewebfontsappname__,d=d?d.toString().substr(0,20):"",e=e.wa.h(O(b),{host:encodeURIComponent(b.j.location.hostname),app:encodeURIComponent(d),_:(+new Date).toString()}),f=new Image(1,1);f.src=e;f.onload=function(){f.onload=l}}e=a.da;e.ja&&(e=e.ja.h(c,b),t(b,"body",e))})}};function La(a,c,b,e,d){this.Qa=a;this.g=c;this.e=b;this.m=e;this.ia=d;this.s=[]}La.prototype.V=function(a){this.s.push(a)};
La.prototype.load=function(a,c){var b=a,e=c||{};if("string"==typeof b)b=[b];else if(!b||!b.length)e=b||{},b=[];if(b.length)for(var d=this,f=b.length,h=0;h<b.length;h++){var j=this.Qa.h(O(this.g),{id:encodeURIComponent(b[h])});xa(this.g,j,function(){0==--f&&Ma(d,e)})}else Ma(this,e)};
function Ma(a,c){if(0!=a.s.length){for(var b=new la(a.g,a.m,c),e=m,d=0;d<a.s.length;d++)a.s[d].init(),e=e||a.s[d].supportsConfiguredBrowser();if(e){v(b.m,b.n.h(b.q,"loading"));I(b,"loading");for(var f=new M(a.e,a.g,b),b=function(a,b,c){f.watch(a,b,{},sa,c)},e=0;e<a.s.length;e++)d=a.s[e],d.supportsConfiguredBrowser()&&(d.load(b,e==a.s.length-1),d.performOptionalActions(window))}else H(b);a.s=[]}}function Na(a,c){this.F=a;this.ia=c;this.s=[]}Na.prototype.V=function(a){this.s.push(a)};
Na.prototype.load=function(){var a=this.F.__webfonttypekitmodule__;if(a)for(var c=0;c<this.s.length;c++){var b=this.s[c],e=a[b.Ca];if(e){var d=this.ia;e(function(a,c,e){c=[];var r={};Ga(b,a);b.supportsConfiguredBrowser()&&(b.init(),b.load(l,d),b.collectFontFamilies(c,r),b.performOptionalActions(window));e(b.supportsConfiguredBrowser(),c,r)})}}};function Oa(a,c){this.ea=a;this.ya=c}Oa.prototype.getName=n("ea");function Pa(a){var c=T;Ha(c,a.getName())||c.ba.push(a)}
function Ha(a,c){for(var b=0;b<a.ba.length;b++){var e=a.ba[b];if(c===e.getName())return e}return l}function Ia(a,c,b){this.g=a;this.t=c;this.o=b}function Ja(a){this.g=a}Ja.prototype.toString=function(){return encodeURIComponent(this.g.Ka?this.g.j.location.hostname:document.location.hostname)};function Ka(a,c){this.t=a;this.o=c}
Ka.prototype.toString=function(){for(var a=[],c=0;c<this.o.length;c++)for(var b=this.o[c],e=b.D(),b=b.D(this.t),d=0;d<e.length;d++){var f;a:{for(f=0;f<b.length;f++)if(e[d]===b[f]){f=k;break a}f=m}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");c=[];for(e=a.length;0<e;e-=4)b=a.slice(0>e-4?0:e-4,e),c.unshift(parseInt(b,2).toString(16));return c.join("")};function U(a){this.Za=a}
U.prototype.h=function(a,c){var b=c||{},e=this.Za.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,c,e){return e&&b[c]?"/"+b[c].join("/"):b[c]||""});e.match(/^\/\//)&&(e=(a?"https:":"http:")+e);return e.replace(/\/*\?*($|\?)/,"$1")};function Qa(a,c,b,e){this.F=a;this.j=c;this.Ma=b;this.ta=e}
Qa.prototype.h=function(a,c){var b=this.j.createElement("img");b.setAttribute("width",62);b.setAttribute("height",25);b.setAttribute("src",this.Ma.h(O(c)));b.setAttribute("class","typekit-badge");b.setAttribute("alt","Fonts by Typekit");b.setAttribute("title","Information about the fonts used on this site");b.style.position="fixed";b.style.zIndex=2E9;b.style.right=0;b.style.bottom=0;b.style.cursor="pointer";b.style.border=0;"Opera"!=a.getName()&&(b.style.content="none");b.style.display="inline";b.style["float"]=
"none";b.style.height="25px";b.style.left="auto";b.style.margin=0;b.style.maxHeight="25px";b.style.maxWidth="62px";b.style.minHeight="25px";b.style.minWidth="62px";b.style.orphans=2;b.style.outline="none";b.style.overflow="visible";b.style.padding=0;b.style.pageBreakAfter="auto";b.style.pageBreakBefore="auto";b.style.pageBreakInside="auto";b.style.tableLayout="auto";b.style.textIndent=0;b.style.top="auto";b.style.unicodeBidi="normal";b.style.verticalAlign="baseline";b.style.visibility="visible";b.style.widows=
2;b.style.width="65px";if(this.ta){var e=this.j,d=this.ta;Ra(this,b,"click",function(){e.location.href=d})}var f=a.getPlatform();if("MSIE"==a.getName()&&"Windows Phone"!=f){b.style.position="absolute";var h=this,j=function(){var a=Sa(h,"scrollLeft","scrollTop"),c=Sa(h,"clientWidth","clientHeight");b.style.bottom="auto";b.style.right="auto";b.style.top=a[1]+c[1]-25+"px";b.style.left=a[0]+c[0]-3-62+"px"};Ra(this,this.F,"scroll",j);Ra(this,this.F,"resize",j)}if("iPhone"==f||"iPod"==f||"iPad"==f||"Android"==
f||"Windows Phone"==f||"BlackBerry"==f)b.style.display="none";return b};function Sa(a,c,b){var e=0,d=0;a=a.j;if(a.documentElement&&(a.documentElement[c]||a.documentElement[b]))e=a.documentElement[c],d=a.documentElement[b];else if(a.body&&(a.body[c]||a.body[b]))e=a.body[c],d=a.body[b];return[e,d]}function Ra(a,c,b,e){if(c.attachEvent){var d=a.F;c["e"+b+e]=e;c[b+e]=function(){c["e"+b+e](d.event)};c.attachEvent("on"+b,c[b+e])}else c.addEventListener(b,e,m)}var Ea=new function(){this.X=[]};
S(new R("air-linux-win","a",function(a,c,b,e,d,f){if(b=m||("Windows"==d&&"Unknown"==f?k:m)||("Ubuntu"==d||"Linux"==d?k:m))a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
S(new R("air-osx","b",function(a,c,b,e,d,f){if(!(b=m))b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m;if(b)a:{if("AdobeAIR"==a&&(a=/([0-9]+.[0-9]+)/.exec(c))){a=2.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
S(new R("builtin-android2to3-android4plus","a",function(a,c,b,e,d,f,h,j){if(!(c=m))b=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=2==c&&2<=b||3==c&&1>b):c=m;c||(f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),j=parseInt(f[2],10),c=4==d&&1<=j||4<d):c=m);return!c?m:"BuiltinBrowser"==a}));
S(new R("builtin-android3to4","f",function(a,c,b,e,d,f,h,j){if(!(c=m))f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),j=parseInt(f[2],10),c=3==d&&1<=j||4==d&&1>j):c=m;return!c?m:"BuiltinBrowser"==a}));S(new R("builtin-bb10plus","d",function(a,c,b,e,d,f,h,j){c=m||j.ka&&10<=parseInt(f,10);return!c?m:"BuiltinBrowser"==a}));
S(new R("chrome4to5-linux-osx-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[3],10),b=10<f||10==f&&4<=b):b="Macintosh"==d&&"Unknown"==f?k:m);if(b=b||("Ubuntu"==d||"Linux"==d?k:m))a:{if("Chrome"==
a&&(d=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c)))if(a=parseFloat(d[1]),c=parseInt(d[2],10),d=parseInt(d[3],10),!(6<=a)&&(4<a||4==a&&249<c||4==a&&249==c&&4<=d)){a=k;break a}a=m}else a=m;return a}));
S(new R("chrome6plus-androidany-chromeos-ipad5plus-iphone5plus-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(e=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[3],10),b=10<b||10==b&&4<=e):b="Macintosh"==d&&"Unknown"==f?k:
m);b=(b=(b=b||("Ubuntu"==d||"Linux"==d?k:m))||j.r&&"Android"==d)||"CrOS"==d;b||(b=j.M&&"iPad"==d?(b=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(b[1],10):m:m);b||(b=j.N&&("iPhone"==d||"iPod"==d)?(d=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(d[1],10):m:m);if(b)a:{if("Chrome"==a&&(a=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c))&&6<=parseFloat(a[1])){a=k;break a}a=g}else a=m;return a}));
S(new R("chrome6plus-ipad4-iphone4","a",function(a,c,b,e,d,f,h,j){if(!(b=m))a:{if(j.M&&"iPad"==d&&(b=/^([0-9]+)_([0-9]+)/.exec(f))){e=parseInt(b[2],10);b=4==parseInt(b[1],10)&&2<=e;break a}b=m}if(!b)a:{if(j.N&&("iPhone"==d||"iPod"==d))if(d=/^([0-9]+)_([0-9]+)/.exec(f)){f=parseInt(d[2],10);b=4==parseInt(d[1],10)&&2<=f;break a}b=m}if(b)a:{if("Chrome"==a&&(a=/([0-9]+.[0-9]+).([0-9]+).([0-9]+)/.exec(c))&&6<=parseFloat(a[1])){a=k;break a}a=g}else a=m;return a}));
S(new R("ff35-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){a=(a=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);a||(a=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&a?(f=parseInt(a[1],10),a=parseInt(a[2],10),a=6<f||6==f&&1<=a):a=m);(a=a||("Ubuntu"==d||"Linux"==d?k:m))?"Gecko"==b?(b=/1.9.1b[1-3]{1}/,e=/1.9.1/.test(e)&&!b.test(e)):e=m:e=m;return e}));
S(new R("ff35-osx","b",function(a,c,b,e,d,f){if(!(a=m))a=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&a?(d=parseInt(a[1],10),f=parseInt(a[3],10),a=10<d||10==d&&4<=f):a="Macintosh"==d&&"Unknown"==f?k:m;a?"Gecko"==b?(b=/1.9.1b[1-3]{1}/,e=/1.9.1/.test(e)&&!b.test(e)):e=m:e=m;return e}));
S(new R("ff36plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){a=(a=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);a||(c=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&c?(a=parseInt(c[1],10),c=parseInt(c[2],10),a=6<a||6==a&&1<=c):a=m);a||(a=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&a?(f=parseInt(a[1],10),a=parseInt(a[3],10),a=10<f||10==f&&4<=a):a="Macintosh"==d&&"Unknown"==f?k:m);if(a=(a=a||("Ubuntu"==d||"Linux"==
d?k:m))||j.r&&"Android"==d)a:{if("Gecko"==b&&(e=/([0-9]+.[0-9]+)(.([0-9]+)|)/.exec(e))){b=parseFloat(e[1]);e=parseInt(e[3],10);b=1.9<b||1.9<=b&&1<e;break a}b=m}else b=m;return b}));
S(new R("ie6to8-win2003-win7plus-winvista-winxp","i",function(a,c,b,e,d,f,h){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(f=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),b=6<d||6==d&&1<=f):b=m);h=b?"MSIE"==a?(a=/([0-9]+.[0-9]+)/.exec(c))?6<=parseFloat(a[1])&&(h===g||9>h):m:g:m;return h}));
S(new R("ie9plus-win7plus-winvista","d",function(a,c,b,e,d,f,h){if(!(c=m))b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(c=parseInt(b[1],10),b=parseInt(b[2],10),c=6<c||6==c&&1<=b):c=m;a=(d=c||("Windows"==d&&"6.0"==f?k:m))?"MSIE"==a?9<=h:g:m;return a}));S(new R("ieany-winphone8plus","d",function(a,c,b,e,d,f,h,j){if(!(c=m))f=/^([0-9]+)/.exec(f),c=j.Da&&"Windows Phone"==d&&f?8<=parseInt(f[1],10):m;return!c?m:"MSIE"==a}));
S(new R("opera10-linux-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(b=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[2],10),b=6<f||6==f&&1<=b):b=m);(b=b||("Ubuntu"==d||"Linux"==d?k:m))?"Opera"==a?(a=parseFloat(c),a=10.54<=a&&11.1>a):a=m:a=m;return a}));
S(new R("opera10-osx","b",function(a,c,b,e,d,f){if(!(b=m))b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m;b?"Opera"==a?(a=parseFloat(c),a=10.54<=a&&11.1>a):a=m:a=m;return a}));
S(new R("opera11plus-androidany-linux-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f,h,j){b=(b=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);b||(e=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=6<b||6==b&&1<=e):b=m);b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[3],10),b=10<f||10==f&&4<=b):b="Macintosh"==d&&"Unknown"==f?k:m);b=(b=b||("Ubuntu"==d||"Linux"==
d?k:m))||j.r&&"Android"==d;return!b?m:"Opera"==a?11.1<=parseFloat(c):m}));S(new R("safari3to5-osx","b",function(a,c,b,e,d,f){if(!(c=m))c=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&c?(d=parseInt(c[1],10),f=parseInt(c[3],10),c=10<d||10==d&&4<=f):c="Macintosh"==d&&"Unknown"==f?k:m;if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&(a=/([0-9]+.[0-9]+)/.exec(e))){a=parseFloat(a[1]);a=525.13<=a&&534.5>a;break a}a=m}else a=m;return a}));
S(new R("safari3to5-win2003-win7plus-winvista-winxp","a",function(a,c,b,e,d,f){c=(c=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);c||(f=/^([0-9]+).([0-9]+)/.exec(f),"Windows"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),c=6<d||6==d&&1<=f):c=m);if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&(a=/([0-9]+.[0-9]+)/.exec(e))){a=parseFloat(a[1]);a=525.13<=a&&534.5>a;break a}a=m}else a=m;return a}));
S(new R("safari5plus-osx-win2003-win7plus-winvista-winxp","d",function(a,c,b,e,d,f){c=(c=m||("Windows"==d&&"5.1"==f?k:m)||("Windows"==d&&"5.2"==f?k:m))||("Windows"==d&&"6.0"==f?k:m);if(!c){var h=/^([0-9]+).([0-9]+)/.exec(f);"Windows"==d&&h?(c=parseInt(h[1],10),h=parseInt(h[2],10),c=6<c||6==c&&1<=h):c=m}c||(c=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&c?(d=parseInt(c[1],10),f=parseInt(c[3],10),c=10<d||10==d&&4<=f):c="Macintosh"==d&&"Unknown"==f?k:m);if(c)a:{if("Safari"==a&&"AppleWebKit"==b&&
(a=/([0-9]+.[0-9]+)/.exec(e))){a=534.5<=parseFloat(a[1]);break a}a=m}else a=m;return a}));
S(new R("safariany-ipad4-iphone4","a",function(a,c,b,e,d,f,h,j){if(!(c=m))a:{if(j.M&&"iPad"==d&&(c=/^([0-9]+)_([0-9]+)/.exec(f))){e=parseInt(c[2],10);c=4==parseInt(c[1],10)&&2<=e;break a}c=m}if(!c)a:{if(j.N&&("iPhone"==d||"iPod"==d))if(f=/^([0-9]+)_([0-9]+)/.exec(f)){j=parseInt(f[2],10);c=4==parseInt(f[1],10)&&2<=j;break a}c=m}return!c?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));
S(new R("safariany-ipad5plus-iphone5plus","d",function(a,c,b,e,d,f,h,j){if(!(c=m))c=j.M&&"iPad"==d?(c=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(c[1],10):m:m;c||(c=j.N&&("iPhone"==d||"iPod"==d)?(f=/^([0-9]+)_([0-9]+)/.exec(f))?5<=parseInt(f[1],10):m:m);return!c?m:"Safari"==a&&"AppleWebKit"==b||"Unknown"==a&&"AppleWebKit"==b&&("iPhone"==d||"iPad"==d)?k:m}));
S(new R("silk1to2-android2to3-osx","a",function(a,c,b,e,d,f,h,j){if(!(b=m))e=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&e?(b=parseInt(e[1],10),e=parseInt(e[2],10),b=2==b&&2<=e||3==b&&1>e):b=m;b||(b=/^([0-9]+)(_|.)([0-9]+)/.exec(f),"Macintosh"==d&&b?(d=parseInt(b[1],10),f=parseInt(b[3],10),b=10<d||10==d&&4<=f):b="Macintosh"==d&&"Unknown"==f?k:m);return!b?m:j.r&&"Silk"==a?2>parseInt(c,10):m}));
S(new R("silk2plus-android3to4-linux","f",function(a,c,b,e,d,f,h,j){if(!(b=m))b=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&b?(f=parseInt(b[1],10),b=parseInt(b[2],10),b=3==f&&1<=b||4==f&&1>b):b=m;d=b||("Ubuntu"==d||"Linux"==d?k:m);return!d?m:j.r&&"Silk"==a?2<=parseInt(c,10):m}));
S(new R("silk2plus-android4plus","a",function(a,c,b,e,d,f,h,j){if(!(b=m))f=/([0-9]+).([0-9]+)/.exec(f),j.r&&"Android"==d&&f?(d=parseInt(f[1],10),f=parseInt(f[2],10),b=4==d&&1<=f||4<d):b=m;return!b?m:j.r&&"Silk"==a?2<=parseInt(c,10):m}));var T=new function(){this.ba=[];this.G={}};Pa(new Oa("AllFonts",function(a,c){return c}));
Pa(new Oa("DefaultFourFontsWithSingleFvdFamilies",function(a,c,b){for(var e=0;e<c.length;e++){var d=c[e],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+d;b.push(new Ca(f,[d]))}a={};for(d=0;d<c.length;d++)b=c[d],e=b.charAt(1),(a[e]||(a[e]=[])).push(b);b=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];e=[];for(d=0;d<b.length;d++)for(var f=b[d],h=0;h<f.length;h++){var j=f[h];if(a[j]){e=e.concat(a[j]);break}}b=e;e={};a=[];for(d=0;d<b.length;d++)f=b[d],e[f]||(e[f]=k,a.push(f));b=[];for(e=0;e<c.length;e++){d=c[e];
for(f=0;f<a.length;f++)h=a[f],h==d&&b.push(h)}return b}));T.G.a="AllFonts";T.G.b="AllFonts";T.G.d="AllFonts";T.G.f="AllFonts";T.G.i="DefaultFourFontsWithSingleFvdFamilies";var W=new function(){this.H={}};W.H.a=[];W.H.b=[];W.H.d=[];W.H.f=["observeddomain"];W.H.i=["observeddomain","fontmask"];var Ta=(new ha(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});
if(!window.Typekit.load){var Ua=window.Typekit.config||{},Va=l;Ua.k&&(Va=new U(Ua.k));var Wa=function(a,c){setTimeout(a,c)},X=new La(Va,new N(window),Ta,document.documentElement,Wa),Y=new Na(window,Wa);window.Typekit.load=function(){X.load.apply(X,arguments)};window.Typekit.addKit=function(){X.V.apply(X,arguments)}}var Xa,Ya=l,Za=l,$a=l,bb,Z,$,Q=window.Typekit.config||{};Q.b&&(Ya=new U(Q.b),Za=new Qa(window,document,Ya,Q.bu));Q.p&&($a=new U(Q.p));bb=new function(){var a=$a;this.ja=Za;this.wa=a};
$=new Fa(new N(window));$.da=bb;Z=new Da;Z.N=!Q.si;Z.M=!Q.st;Z.r=!Q.sa;Z.Da=!Q.sw;Z.ka=!Q.sb;$.la=Z;Q.w&&($.Ca=Q.w);Q.f&&(Xa=new U(Q.f),$.Z=Xa);var i;if(Q.fn)for(i=0;i<Q.fn.length;i+=2)$.o.push(new Aa(Q.fn[i],Q.fn[i+1]));if(Q.c)for(i=0;i<Q.c.length;i+=2)$.Q.push(new ya);$.Y=W;$.W=Ea;$.aa=T;var cb;if(cb=Y)cb=!!Y.F.__webfonttypekitmodule__;cb?(Y.V($),Y.load()):(Ga($,Ta),window.Typekit.addKit($));
})(this,document);
